### PR TITLE
Added reflection to ThemeCompilerPass to address changes made in symf…

### PR DESCRIPTION
**Pull request by fotomerchant**
Added reflection to ThemeCompilerPass to address changes made in https://github.com/symfony/symfony/commit/2d4268936a05254a4e8b2d1ed7d2fc08881a098b which should address https://github.com/liip/LiipThemeBundle/issues/157

### CODE REVIEW

**Comment by fotomerchant** [comment]
In termes of the tests, I didn't have time to figure out how to create the appropriate Mocks for the ThemeCompilerPass since it's now using Reflection. If anyone has any ideas I'll take them :)

**Comment by Sander-Toonen** [comment]
Symfony 3.2.1 just got released, resulting in #157.

Test are broken but I can confirm that the PR successfully solves the issue when running Symfony 3.2.1, also it doesn't break BC (tested in Symfony 3.2.0)

**Comment by fotomerchant** [comment]
Yeah, the tests are broken because my method of fixing it was to enhance the ThemeCompilerPass with reflection. However, my experience with creating Mocks in unit tests is limited and I haven't had the time to figure out how to create a Mock complex enough to pass the unit tests. 

If there is someone out there with more experience with Mocks then they might be able to get it working and then I can add a few more tests to handle both pre and post Symfony 3.2.1 scenarios.

**Comment by lsmith77** [comment]
does anyone have time to look into fixing the tests?

**Comment by oleg-andreyev** [comment]
Was planning to help today

**Comment by j0k3r** [comment]
While it might fix the problem for LiipThemeBundle, won't this generate this error when warming up the cache https://github.com/twigphp/Twig/issues/2281 ?

Instead of this reflexion hack, why not changing the constructor to be compatible with the new `FilesystemLoader` from TwigBundle and use an extra method call to set the active theme?

In `ThemeCompilerPass`:
```diff
         $twigFilesystemLoaderDefinition = $container->getDefinition('twig.loader.filesystem');
         $twigFilesystemLoaderDefinition->setClass($container->getParameter('liip_theme.filesystem_loader.class'));
-        $twigFilesystemLoaderDefinition->addArgument(new Reference('liip_theme.active_theme'));
+        $twigFilesystemLoaderDefinition->addMethodCall('setActiveTheme', [new Reference('liip_theme.active_theme')]);
```

In `FilesystemLoader`:

```diff
     /**
      * Constructor.
      *
-     * @param FileLocatorInterface        $locator     A FileLocatorInterface instance
-     * @param TemplateNameParserInterface $parser      A TemplateNameParserInterface instance
-     * @param ActiveTheme                 $activeTheme
+     * @param FileLocatorInterface        $locator  A FileLocatorInterface instance
+     * @param TemplateNameParserInterface $parser   A TemplateNameParserInterface instance
+     * @param string|null                 $rootPath The root path common to all relative paths (null for getcwd())
      */
-    public function __construct(FileLocatorInterface $locator, TemplateNameParserInterface $parser, ActiveTheme $activeTheme = null)
+    public function __construct(FileLocatorInterface $locator, TemplateNameParserInterface $parser, $rootPath = null)
     {
-        parent::__construct(array());
+        parent::__construct(array(), $rootPath);
+
         $this->locator = $locator;
         $this->parser = $parser;
+    }
+
+    /**
+     * Define the active theme
+     *
+     * @param ActiveTheme $activeTheme
+     */
+    public function setActiveTheme(ActiveTheme $activeTheme = null)
+    {
         $this->activeTheme = $activeTheme;
     }
```

**Comment by lsmith77** [comment]
Would definitely prefer a solution without reflection .. @j0k3r maybe open your approach as a PR too?

**Comment by fotomerchant** [comment]
I agree this is a cleaner fix than adding then using reflection in https://github.com/liip/LiipThemeBundle/pull/158.

**Comment by lsmith77** [comment]
superseded by #159

**Pull request closed without merging**
