### PR TITLE
Change confusing example themes names

### PR DESCRIPTION
**Pull request by ahilles107**
Old names mixed devices parameters with themes names.

### CODE REVIEW

**Comment by lsmith77** [comment]
the theme names are like this because originally we planned to use theming to have different UIs for desktop/tablet/phone .. in the end we decided that responsive UI was enough so we didn't even use this Bundle.

**Comment by lsmith77** [comment]
so I guess my question is .. why do you think these theme names are confusing?

**Comment by ahilles107** [comment]
Because we have that feature for choosing template based on device type (```current_device```) witch is separate thing. And first impression about ```autodetect_theme``` tells me that it will change theme (from web to tabled on ipad device) witch isn't true - it will just setup correct value under ```current_device`` parameter. Maybe i should add small chapter about this also?

**Comment by lsmith77** [comment]
that sounds like a good suggestion

**Comment by ahilles107** [comment]
Please check how it looks.

**Comment by lsmith77** [comment]
nice

**Pull request merged**
