### PR TITLE
Removing setCurrentTheme on FileLoctor constructor

### PR DESCRIPTION
**Pull request by gtrias**
This statement avoids device autodetection to work. Changed the line to lastTheme setting that way it doesn't break the lastTheme tests.

### CODE REVIEW

**Comment by lsmith77** [comment]
hmm .. did you investigate how/when/why the faulty code was introduced?

**Comment by gtrias** [comment]
Not so much, what it does?
Autodetection just doesn't work with this setter. I'm missing anything in config files?

**Comment by lsmith77** [comment]
I was able to reproduce the issue, but I also applied a follow up fix 2a370bd

**Comment by lsmith77** [comment]
I fear in order to properly test for this .. we will need to add some functional tests

**Comment by lsmith77** [comment]
seems like this is breaking asset dumping https://github.com/liip/LiipThemeBundle/issues/114

**Pull request merged**
