### PR TITLE
compatibility of FilesystemLoader with Twig 2.0

### LINKED ISSUE #161: Problems overriding twig file systemloader (twig 2.0)
I just had the issue, that I had twig 2.0 in my vendors (still have to figure out why), and tried to install the theme bundle.

That resulted in following warning:

> PHP Warning:  Declaration of Liip\ThemeBundle\Twig\Loader\FilesystemLoader::findTemplate($template) should be compatible with Twig_Loader_Filesystem::findTemplate($name, $throw = true) in /srv/www/bestfewo.de/vendor/liip/theme-bundle/Twig/Loader/FilesystemLoader.php on line 10

Turns out the filesystem loader has a second parameter in twig 2.0, but isn't implemented in the overriding class.

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #161.

### CODE REVIEW

**Comment by lsmith77** [comment]
guess this one needs to be rebased on master since I merged your #163 PR

**Comment by xabbuh** [comment]
Rebased, the build is green now.

**Comment by oleg-andreyev** [comment]
I'd suggest adjusting phpUnit to fail on warnings.

**Comment by xabbuh** [comment]
Which warnings do you mean?

**Comment by oleg-andreyev** [comment]
phpUnit has `convertWarningsToExceptions` so if warning will be raised it would be converted to exception and test would fail (if we have such)

**Comment by xabbuh** [comment]
That's PHPUnit's default behaviour. But I still don't see how that is related to this PR.

**Comment by lsmith77** [comment]
yeah if there is something to adjust there, lets do it in another PR

**Pull request merged**
