### PR TITLE
Fix compiler pass order

### LINKED ISSUE #183: Compiler passes are running to early
Ever since I've upgraded from 1.4.6 to 1.5.1 I get the following message:

> You have requested a non-existent service "assetic.twig_directory_resource.BundleName".

Turns out that due to https://github.com/liip/LiipThemeBundle/commit/1cce39fd2fc1a48ef0d35794bcdcaf68af6aa56e the LiipTheme compiler passes are running _after_ the compiler passes from AsseticBundle.

The services are defined in Assetics' TemplateResourcesPass which runs during the TYPE_BEFORE_OPTIMIZATION phase with priority 0. LiipThemes' TemplateResourcesPass runs in the same phase, but with priority 10, changing this to -10 should solve the issue.

### PR DESCRIPTION
**Pull request by Sander-Toonen**
Fixes #183

### CODE REVIEW

**Comment by lsmith77** [comment]
ok thx for the PR .. I will investigate. I have a very simplistic test setup as I don't use the Bundle but for me adding those priorities fixed issues I was seeing with Symfony 4 ..

**Comment by lsmith77** [comment]
will check in my Symfony 2.7 test setup ..

**Comment by lsmith77** [comment]
hmm I guess none of my test setups leverage Assetic.
but I guess you are right .. higher priorities get called first. but then the other compiler pass also needs to get a negative priority. can you also make that adjustment?

thx for the quick report and PR!

**Comment by elonmir** [comment]
Thank you, nearly bricked our production system until I pinned the old version, gonna try the new setup.

**Comment by elonmir** [comment]
Can confirm that the fix seems to work.

**Comment by lsmith77** [comment]
https://github.com/liip/LiipThemeBundle/releases/tag/1.5.2

would obviously be good to add a functional test to prevent this regression in the future ..

**Pull request merged**
